name: Blog CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Seje Theme Repository
        uses: actions/checkout@v3
        with:
          repository: GoodbyeNJN/Seje-nextjs

      - name: Checkout Blog Repository
        uses: actions/checkout@v3
        with:
          path: blog

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Get pnpm Store Directory
        id: pnpm-cache
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and Export
        run: npm run build

      - name: Archive Dist Files
        uses: thedoctor0/zip-release@main
        with:
          type: "zip"
          filename: "release.zip"
          directory: "out"
          path: "./*"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: out/release.zip

      - name: Trigger Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
